# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='float_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='int_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='float_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='int_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
